# Unnecessary file just to fix port issue for localhost

spec:
  template:
    spec:
      containers:
        - name: ingress-nginx-controller
          ports:
            - containerPort: 6379
              hostPort: 6379
