apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: database
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: client
      port: 6379
      targetPort: 6379
    - protocol: TCP
      name: gossip
      port: 16379
      targetPort: 16379
  selector:
    app: redis-sts
