# apiVersion: v1
# kind: Service
# metadata:
#     name: redis-service
#     namespace: database
# spec:
#     selector:
#         app: redis
#     ports:
#         - protocol: TCP
#           port: 6379
#           targetPort: 6379

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: database
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: client
    - port: 16379
      targetPort: 16379
      name: gossip
  selector:
    app: redis-sts
