apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
        - name: api
          image: api:0.1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: database-url
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
